version: "3.9"
services:
  pg_db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  scrapper:
    build: .
    depends_on:
      pg_db:
        condition: service_healthy
